### PR TITLE
Updating the OCaml template to be a little more modern.

### PR DESCRIPTION
**Pull request by dclements**
* Downloads some of the optional dependencies for OPAM to make sure they are available.
* Moves the downloaded dependencies to the /workspace directory.
* Moves the code out of a subdirectory and into the main directory.
* Regenerated the project to more closely match the structure of modern dune projects.
* Added some vscode configs that are recommended and some additional plugins as recommended.
* Updated the docs.
* Adds more .gitignore items for vscode.
* Copious notes.

### CODE REVIEW

**Comment by axonasif** [comment]
Thanks for contributing @dclements!

Can you please check if this also works with [prebuilds enabled](https://www.gitpod.io/docs/configure/projects/prebuilds#enable-prebuilds-on-your-repository-project)? I ask because there seems to be quite a lot of new things happening through an `init` task on the proposed `.gitpod.yml`.

**Comment by dclements** [comment]
It works for me with prebuilds enabled: https://gitpod.io/projects/template-ocaml/252defc8-1d68-4180-9c7f-fb4a31c5db3e leading to https://dclements-templateocaml-w03albjk06g.ws-us104.gitpod.io/

The logic needed to be moved out of the docker configuration due to it now writing to /workspace for dependencies, much like how dependencies are managed now with gradle.

Also notable is that the previous version [doesn't work in prebuilds at all](https://gitpod.io/projects/template-ocaml/278059df-c8c7-4aef-ae31-e74e4a462d35).

**Comment by axonasif** [comment]
That's great. Thanks for checking 🙏

**Comment by axonasif** [comment]
And BTW, I invite you to join our discord server if you haven't yet! 😄 
https://www.gitpod.io/chat

**Pull request merged**
